### ISSUE TITLE
Deploying and hosting the app on Heroku/Netlify

### ISSUE THREAD

**Issue by gennady9** [gennady9/fast-food-reviews#2]

**Comment by shardul-b** [comment]
Maybe this would help:
https://www.netlify.com/blog/2016/10/27/a-step-by-step-guide-deploying-a-static-site-or-single-page-app/

**Comment by prateek1998** [comment]
please assign this issue to me.

**Comment by Ayush-Khandelwal-007** [comment]
Please assign it to me.
I can host it on which ever you want.
